// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sparcpoint.Core.Persistence.Entity.Sparcpoint.Entities
{
    public partial class Product
    {
        public Product()
        {
            InventoryTransactions = new HashSet<InventoryTransaction>();
            ProductAttributes = new HashSet<ProductAttribute>();
            CategoryInstances = new HashSet<Category>();
        }

        public int InstanceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ProductImageUris { get; set; }
        public string ValidSkus { get; set; }
        public DateTime CreatedTimestamp { get; set; }

        public virtual ICollection<InventoryTransaction> InventoryTransactions { get; set; }
        public virtual ICollection<ProductAttribute> ProductAttributes { get; set; }

        public virtual ICollection<Category> CategoryInstances { get; set; }
    }
}