// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sparcpoint.Inventory.Model
{
    public partial class CategoryCategories
    {
        public int InstanceId { get; set; }
        public int CategoryInstanceId { get; set; }

        public virtual Categories CategoryInstance { get; set; }
        public virtual Categories Instance { get; set; }
    }
}