// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sparcpoint.Inventory.Model
{
    public partial class Categories
    {
        public Categories()
        {
            CategoryAttributes = new HashSet<CategoryAttributes>();
            CategoryCategoriesCategoryInstance = new HashSet<CategoryCategories>();
            CategoryCategoriesInstance = new HashSet<CategoryCategories>();
            ProductCategories = new HashSet<ProductCategories>();
        }

        public int InstanceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime CreatedTimestamp { get; set; }

        public virtual ICollection<CategoryAttributes> CategoryAttributes { get; set; }
        public virtual ICollection<CategoryCategories> CategoryCategoriesCategoryInstance { get; set; }
        public virtual ICollection<CategoryCategories> CategoryCategoriesInstance { get; set; }
        public virtual ICollection<ProductCategories> ProductCategories { get; set; }
    }
}