// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sparcpoint.Inventory.Model
{
    public partial class Products
    {
        public Products()
        {
            InventoryTransactions = new HashSet<InventoryTransactions>();
            ProductAttributes = new HashSet<ProductAttributes>();
            ProductCategories = new HashSet<ProductCategories>();
        }

        public int InstanceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ProductImageUris { get; set; }
        public string ValidSkus { get; set; }
        public DateTime CreatedTimestamp { get; set; }

        public virtual ICollection<InventoryTransactions> InventoryTransactions { get; set; }
        public virtual ICollection<ProductAttributes> ProductAttributes { get; set; }
        public virtual ICollection<ProductCategories> ProductCategories { get; set; }
    }
}