// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Sparkpoint.Data
{
    // CategoryAttributes
    public class CategoryAttributeConfiguration : IEntityTypeConfiguration<CategoryAttribute>
    {
        public void Configure(EntityTypeBuilder<CategoryAttribute> builder)
        {
            builder.ToTable("CategoryAttributes", "Instances");
            builder.HasKey(x => new { x.InstanceId, x.Key }).HasName("PK_CategoryAttributes").IsClustered();

            builder.Property(x => x.InstanceId).HasColumnName(@"InstanceId").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Key).HasColumnName(@"Key").HasColumnType("varchar(64)").IsRequired().IsUnicode(false).HasMaxLength(64).ValueGeneratedNever();
            builder.Property(x => x.Value).HasColumnName(@"Value").HasColumnType("varchar(512)").IsRequired().IsUnicode(false).HasMaxLength(512);

            // Foreign keys
            builder.HasOne(a => a.Category).WithMany(b => b.CategoryAttributes).HasForeignKey(c => c.InstanceId).HasConstraintName("FK_CategoryAttributes_Categories");
        }
    }

}
// </auto-generated>
