// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Sparkpoint.Data
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // Categories
    public class CategoryConfiguration : IEntityTypeConfiguration<Category>
    {
        public void Configure(EntityTypeBuilder<Category> builder)
        {
            builder.ToTable("Categories", "Instances");
            builder.HasKey(x => x.InstanceId).HasName("PK__Categori__5C51994F45948AD1").IsClustered();

            builder.Property(x => x.InstanceId).HasColumnName(@"InstanceId").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar(64)").IsRequired().IsUnicode(false).HasMaxLength(64);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar(256)").IsRequired().IsUnicode(false).HasMaxLength(256);
            builder.Property(x => x.CreatedTimestamp).HasColumnName(@"CreatedTimestamp").HasColumnType("datetime2").IsRequired();
        }
    }

}
// </auto-generated>
