// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Sparkpoint.Data
{
    // ProductAttributes
    public class ProductAttributeConfiguration : IEntityTypeConfiguration<ProductAttribute>
    {
        public void Configure(EntityTypeBuilder<ProductAttribute> builder)
        {
            builder.ToTable("ProductAttributes", "Instances");
            builder.HasKey(x => new { x.InstanceId, x.Key }).HasName("PK_ProductAttributes").IsClustered();

            builder.Property(x => x.InstanceId).HasColumnName(@"InstanceId").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Key).HasColumnName(@"Key").HasColumnType("varchar(64)").IsRequired().IsUnicode(false).HasMaxLength(64).ValueGeneratedNever();
            builder.Property(x => x.Value).HasColumnName(@"Value").HasColumnType("varchar(512)").IsRequired().IsUnicode(false).HasMaxLength(512);

            // Foreign keys
            builder.HasOne(a => a.Product).WithMany(b => b.ProductAttributes).HasForeignKey(c => c.InstanceId).HasConstraintName("FK_ProductAttributes_Products");

            builder.HasIndex(x => new { x.Key, x.Value }).HasName("IX_ProductAttributes_Key_Value");
        }
    }

}
// </auto-generated>
