// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Sparkpoint.Data
{
    // ProductCategories
    public class ProductCategoryConfiguration : IEntityTypeConfiguration<ProductCategory>
    {
        public void Configure(EntityTypeBuilder<ProductCategory> builder)
        {
            builder.ToTable("ProductCategories", "Instances");
            builder.HasKey(x => new { x.InstanceId, x.CategoryInstanceId }).HasName("PK_ProductCategories").IsClustered();

            builder.Property(x => x.InstanceId).HasColumnName(@"InstanceId").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.CategoryInstanceId).HasColumnName(@"CategoryInstanceId").HasColumnType("int").IsRequired().ValueGeneratedNever();

            // Foreign keys
            builder.HasOne(a => a.Category).WithMany(b => b.ProductCategories).HasForeignKey(c => c.CategoryInstanceId).HasConstraintName("FK_ProductCategories_Categories");
            builder.HasOne(a => a.Product).WithMany(b => b.ProductCategories).HasForeignKey(c => c.InstanceId).HasConstraintName("FK_ProductCategories_Products");
        }
    }

}
// </auto-generated>
