GET https://localhost:44387/api/v1/products/all
Content-Type: application/json

###

POST https://localhost:44387/api/v1/products/create
Content-Type: application/json

{
  "Name": "Product 1",
  "Description": "Product 1 description",
  "ProductImageUris": "/testimageurl",
  "ValidSkus": "JU234343"
}

###

GET https://localhost:44387/api/v1/products/1
Content-Type: application/json

###

PUT https://localhost:44387/api/v1/products/update
Accept: application/json
Content-Type: application/json

{
  "instanceId": 1,
  "name": "test update",
  "description": "test update description",
  "productImageUris": "/test/url/path",
  "validSkus": "testsku"
}