using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Interview.Web.Models;
using Interview.Web.Repositories.Interfaces;
using Sparcpoint.SqlServer.Abstractions;

namespace Interview.Web.Repositories.Implementations;

public class ProductRepository : IProductRepository
{
    private readonly ISqlExecutor _sqlExecutor;

    public ProductRepository(ISqlExecutor sqlExecutor)
    {
        _sqlExecutor = sqlExecutor;
    }

    public async Task<int> CreateAsync(CreateProductRequest request)
    {
        return await _sqlExecutor.ExecuteAsync(async (conn, trans) =>
        {
            // EVAL: SCOPE_IDENTITY() returns the auto-incremented InstanceId generated by the
            // INSERT, scoped to the current connection so concurrent inserts don't collide.
            const string insertProduct = @"
                INSERT INTO Instances.Products (Name, Description, ValidSkus, ProductImageUris)
                VALUES (@Name, @Description, @ValidSkus, @ProductImageUris);
                SELECT CAST(SCOPE_IDENTITY() AS INT);";

            var id = await conn.ExecuteScalarAsync<int>(insertProduct, new
            {
                request.Name,
                Description = request.Description ?? string.Empty,
                // EVAL: Arrays are stored as comma-separated strings to match the VARCHAR(MAX)
                // schema design. The schema allows this without additional tables.
                ValidSkus = string.Join(",", request.ValidSkus ?? Array.Empty<string>()),
                ProductImageUris = string.Join(",", request.ProductImageUris ?? Array.Empty<string>())
            }, trans);

            if (request.Attributes != null && request.Attributes.Any())
            {
                const string insertAttribute = @"
                    INSERT INTO Instances.ProductAttributes (InstanceId, [Key], [Value])
                    VALUES (@InstanceId, @Key, @Value);";

                foreach (var attr in request.Attributes)
                {
                    await conn.ExecuteAsync(insertAttribute, new
                    {
                        InstanceId = id,
                        Key = attr.Key,
                        Value = attr.Value
                    }, trans);
                }
            }

            if (request.CategoryIds != null && request.CategoryIds.Any())
            {
                const string insertCategory = @"
                    INSERT INTO Instances.ProductCategories (InstanceId, CategoryInstanceId)
                    VALUES (@InstanceId, @CategoryInstanceId);";

                foreach (var categoryId in request.CategoryIds)
                {
                    await conn.ExecuteAsync(insertCategory, new
                    {
                        InstanceId = id,
                        CategoryInstanceId = categoryId
                    }, trans);
                }
            }

            return id;
        });
    }

    public Task<IEnumerable<Product>> SearchAsync(ProductSearchRequest request)
        => throw new NotImplementedException();
}
