// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Sparkpoint.Data
{
    // CategoryAttributes
    public class CategoryAttribute
    {
        public int InstanceId { get; set; } // InstanceId (Primary key)
        public string Key { get; set; } // Key (Primary key) (length: 64)
        public string Value { get; set; } // Value (length: 512)

        // Foreign keys

        /// <summary>
        /// Parent Category pointed by [CategoryAttributes].([InstanceId]) (FK_CategoryAttributes_Categories)
        /// </summary>
        public Category Category { get; set; } // FK_CategoryAttributes_Categories
    }

}
// </auto-generated>
