// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Sparkpoint.Data
{
    // CategoryCategories
    public class CategoryCategory
    {
        public int InstanceId { get; set; } // InstanceId (Primary key)
        public int CategoryInstanceId { get; set; } // CategoryInstanceId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Category pointed by [CategoryCategories].([CategoryInstanceId]) (FK_CategoryCategories_Categories_Categories)
        /// </summary>
        public Category CategoryInstance { get; set; } // FK_CategoryCategories_Categories_Categories

        /// <summary>
        /// Parent Category pointed by [CategoryCategories].([InstanceId]) (FK_CategoryCategories_Categories)
        /// </summary>
        public Category Instance { get; set; } // FK_CategoryCategories_Categories
    }

}
// </auto-generated>
