// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Sparkpoint.Data
{
    // ProductCategories
    public class ProductCategory
    {
        public int InstanceId { get; set; } // InstanceId (Primary key)
        public int CategoryInstanceId { get; set; } // CategoryInstanceId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Category pointed by [ProductCategories].([CategoryInstanceId]) (FK_ProductCategories_Categories)
        /// </summary>
        public Category Category { get; set; } // FK_ProductCategories_Categories

        /// <summary>
        /// Parent Product pointed by [ProductCategories].([InstanceId]) (FK_ProductCategories_Products)
        /// </summary>
        public Product Product { get; set; } // FK_ProductCategories_Products
    }

}
// </auto-generated>
