// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Sparkpoint.Data
{
    // ProductAttributes
    public class ProductAttribute
    {
        public int InstanceId { get; set; } // InstanceId (Primary key)
        public string Key { get; set; } // Key (Primary key) (length: 64)
        public string Value { get; set; } // Value (length: 512)

        // Foreign keys

        /// <summary>
        /// Parent Product pointed by [ProductAttributes].([InstanceId]) (FK_ProductAttributes_Products)
        /// </summary>
        public Product Product { get; set; } // FK_ProductAttributes_Products
    }

}
// </auto-generated>
