// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Sparkpoint.Data
{
    // Products
    public class Product
    {
        public int InstanceId { get; set; } // InstanceId (Primary key)
        public string Name { get; set; } // Name (length: 256)
        public string Description { get; set; } // Description (length: 256)
        public string ProductImageUris { get; set; } // ProductImageUris
        public string ValidSkus { get; set; } // ValidSkus
        public bool IsActive { get; set; } // IsActive
        public DateTime CreatedTimestamp { get; set; } // CreatedTimestamp

        // Reverse navigation

        /// <summary>
        /// Child InventoryTransactions where [InventoryTransactions].[ProductInstanceId] point to this entity (FK_InventoryTransactions_Products)
        /// </summary>
        public ICollection<InventoryTransaction> InventoryTransactions { get; set; } // InventoryTransactions.FK_InventoryTransactions_Products

        /// <summary>
        /// Child ProductAttributes where [ProductAttributes].[InstanceId] point to this entity (FK_ProductAttributes_Products)
        /// </summary>
        public ICollection<ProductAttribute> ProductAttributes { get; set; } // ProductAttributes.FK_ProductAttributes_Products

        /// <summary>
        /// Child ProductCategories where [ProductCategories].[InstanceId] point to this entity (FK_ProductCategories_Products)
        /// </summary>
        public ICollection<ProductCategory> ProductCategories { get; set; } // ProductCategories.FK_ProductCategories_Products

        public Product()
        {
            IsActive = true;
            CreatedTimestamp = DateTime.UtcNow;
            InventoryTransactions = new List<InventoryTransaction>();
            ProductAttributes = new List<ProductAttribute>();
            ProductCategories = new List<ProductCategory>();
        }
    }

}
// </auto-generated>
