using System;
using System.Collections.Generic;

namespace Sparcpoint.Inventory.Models
{
    /// <summary>
    /// Represents a product category, supporting hierarchical relationships.
    /// Maps to the [Instances].[Categories] table.
    /// </summary>
    public class Category
    {
        /// <summary>
        /// Unique identifier for the category. Auto-generated by the database.
        /// </summary>
        public int InstanceId { get; set; }

        /// <summary>
        /// Display name of the category.
        /// DB constraint: VARCHAR(64)
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Category description.
        /// DB constraint: VARCHAR(256)
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// UTC timestamp of when this category was created.
        /// </summary>
        public DateTime CreatedTimestamp { get; set; }

        /// <summary>
        /// Arbitrary key-value metadata for this category.
        /// Maps to [Instances].[CategoryAttributes].
        /// </summary>
        public Dictionary<string, string> Attributes { get; set; } = new Dictionary<string, string>();

        /// <summary>
        /// Parent category IDs in the hierarchy.
        /// Maps to [Instances].[CategoryCategories].
        /// </summary>
        // EVAL: A category can belong to multiple parent categories,
        // enabling flexible hierarchies (e.g., "Wireless Headphones" under both
        // "Electronics > Audio" and "Accessories").
        public List<int> ParentCategoryIds { get; set; } = new List<int>();
    }
}
