using System;

namespace Sparcpoint.Inventory.Models
{
    /// <summary>
    /// Represents a single inventory transaction (add or remove).
    /// Maps to [Transactions].[InventoryTransactions].
    /// </summary>
    // EVAL: Inventory is tracked via an append-only transaction log rather than
    // a mutable "current count" field. This design supports full auditability
    // and the "undo" requirement -- reversing a transaction doesn't lose history,
    // it marks CompletedTimestamp, excluding it from active count calculations.
    public class InventoryTransaction
    {
        /// <summary>
        /// Unique transaction identifier. Auto-generated by the database.
        /// </summary>
        public int TransactionId { get; set; }

        /// <summary>
        /// The product this transaction applies to.
        /// FK to [Instances].[Products].[InstanceId].
        /// </summary>
        public int ProductInstanceId { get; set; }

        /// <summary>
        /// Quantity added (positive) or removed (negative).
        /// DB constraint: DECIMAL(19,6) -- supports fractional units (e.g., 2.5 kg).
        /// </summary>
        // RV: Positive = inventory added, Negative = inventory removed.
        // This convention keeps the count calculation simple: SUM(Quantity) WHERE CompletedTimestamp IS NULL.
        public decimal Quantity { get; set; }

        /// <summary>
        /// When the transaction was initiated.
        /// </summary>
        public DateTime StartedTimestamp { get; set; }

        /// <summary>
        /// When the transaction was completed/undone. NULL = active transaction.
        /// </summary>
        // EVAL: CompletedTimestamp serves as a soft-delete flag.
        // Active transactions (NULL) are included in inventory counts.
        // Undone transactions (non-NULL) are excluded but preserved for audit.
        public DateTime? CompletedTimestamp { get; set; }

        /// <summary>
        /// Classification of the transaction (e.g., "Purchase", "Sale", "Return", "Adjustment").
        /// DB constraint: VARCHAR(32)
        /// </summary>
        public string TypeCategory { get; set; }

        /// <summary>
        /// Whether this transaction is currently active (not undone).
        /// </summary>
        public bool IsActive => CompletedTimestamp == null;
    }
}
