// EVAL: Domain models are kept in a separate library (Sparcpoint.Inventory) from the
// web project and data access layer. This enforces clean architecture boundaries --
// the domain knows nothing about HTTP or SQL.

using System;
using System.Collections.Generic;

namespace Sparcpoint.Inventory.Models
{
    /// <summary>
    /// Represents a product in the inventory system.
    /// Maps to the [Instances].[Products] table.
    /// </summary>
    public class Product
    {
        /// <summary>
        /// Unique identifier for the product. Auto-generated by the database.
        /// </summary>
        public int InstanceId { get; set; }

        /// <summary>
        /// Display name of the product.
        /// DB constraint: VARCHAR(256)
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Product description.
        /// DB constraint: VARCHAR(256)
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Product image URIs.
        /// Stored as JSON in the DB (VARCHAR(MAX)), deserialized at the repository layer.
        /// </summary>
        // EVAL: Domain model exposes native List instead of raw JSON string.
        // Serialization/deserialization is handled by the repository, keeping
        // the storage format as an infrastructure concern.
        public List<string> ProductImageUris { get; set; } = new List<string>();

        /// <summary>
        /// Valid SKUs for this product.
        /// Stored as JSON in the DB (VARCHAR(MAX)), deserialized at the repository layer.
        /// </summary>
        public List<string> ValidSkus { get; set; } = new List<string>();

        /// <summary>
        /// UTC timestamp of when this product was created.
        /// </summary>
        public DateTime CreatedTimestamp { get; set; }

        /// <summary>
        /// Arbitrary key-value metadata for this product (e.g., Color, Brand, Size).
        /// Maps to [Instances].[ProductAttributes].
        /// </summary>
        // EVAL: Dictionary allows truly arbitrary metadata per the requirements.
        // The key constraint (VARCHAR 64) and value constraint (VARCHAR 512) are
        // enforced at the validation layer, not here, keeping the domain model clean.
        public Dictionary<string, string> Attributes { get; set; } = new Dictionary<string, string>();

        /// <summary>
        /// Category IDs this product belongs to.
        /// Maps to [Instances].[ProductCategories].
        /// </summary>
        public List<int> CategoryIds { get; set; } = new List<int>();

        /// <summary>
        /// Category details (ID -> Name) for this product.
        /// Populated by repository queries that JOIN to [Instances].[Categories].
        /// </summary>
        public Dictionary<int, string> Categories { get; set; } = new Dictionary<int, string>();
    }
}
